name: Build

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 12
      
    - name: Build
      run: ./gradlew clean build jacocoTestReport
      
      if: success()
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
