name: Java CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 12
      
    - name: Build with Gradle
      run: ./gradlew clean build jacocoTestReport
      
      if: success()
    - name: Send coverage
      run:  bash <(curl -s https://codecov.io/bash)
      shell: bash 
